homeを作成
kip-i/grofessor pull request #7
Opened 2023-12-02 07:24 UTC by kip-i

フッターの呼び出し
フッターで呼び出し
HomeSelectorでduringTimeかdefaultかを呼び出す。

2023-12-03 06:01 UTC, ryu-k67 requested changes

2023-12-03 06:01 UTC, ryu-k67 commented on pubspec.yaml
> +  flutter_cube: ^0.1.1
flutter_cubのインストールが2回記述されている
エラー発生する

2023-12-03 07:12 UTC, kip-i commented on pubspec.yaml
> +  flutter_cube: ^0.1.1
ナイス
消しといた

2023-12-03 07:22 UTC, sekibuuun commented
pubspec.lock
`  fading_edge_scrollview:
    dependency: transitive
    description:
      name: fading_edge_scrollview
      sha256: c25c2231652ce774cc31824d0112f11f653881f43d7f5302c05af11942052031
      url: "https://pub.dev"
    source: hosted
    version: "3.0.0"`
 
 GeneratedPluginRegistrant.swift
 `//
//  Generated file. Do not edit.
//

import FlutterMacOS
import Foundation

import cloud_firestore
import firebase_auth
import firebase_core
import firebase_storage
import shared_preferences_foundation

func RegisterGeneratedPlugins(registry: FlutterPluginRegistry) {
  FLTFirebaseFirestorePlugin.register(with: registry.registrar(forPlugin: "FLTFirebaseFirestorePlugin"))
  FLTFirebaseAuthPlugin.register(with: registry.registrar(forPlugin: "FLTFirebaseAuthPlugin"))
  FLTFirebaseCorePlugin.register(with: registry.registrar(forPlugin: "FLTFirebaseCorePlugin"))
  FLTFirebaseStoragePlugin.register(with: registry.registrar(forPlugin: "FLTFirebaseStoragePlugin"))
  SharedPreferencesPlugin.register(with: registry.registrar(forPlugin: "SharedPreferencesPlugin"))
}`

Runしたら、コード追加されたけど大丈夫そう？

2023-12-03 08:24 UTC, ryu-k67 commented
@sekibuuun
無視でいいはず
パッケージのインストールに伴う自動追加

2023-12-04 06:53 UTC, sekibuuun commented
> pubspec.lock ` fading_edge_scrollview: dependency: transitive description: name: fading_edge_scrollview sha256: c25c2231652ce774cc31824d0112f11f653881f43d7f5302c05af11942052031 url: "https://pub.dev" source: hosted version: "3.0.0"`
> 
> GeneratedPluginRegistrant.swift `// // Generated file. Do not edit. //
> 
> import FlutterMacOS import Foundation
> 
> import cloud_firestore import firebase_auth import firebase_core import firebase_storage import shared_preferences_foundation
> 
> func RegisterGeneratedPlugins(registry: FlutterPluginRegistry) { FLTFirebaseFirestorePlugin.register(with: registry.registrar(forPlugin: "FLTFirebaseFirestorePlugin")) FLTFirebaseAuthPlugin.register(with: registry.registrar(forPlugin: "FLTFirebaseAuthPlugin")) FLTFirebaseCorePlugin.register(with: registry.registrar(forPlugin: "FLTFirebaseCorePlugin")) FLTFirebaseStoragePlugin.register(with: registry.registrar(forPlugin: "FLTFirebaseStoragePlugin")) SharedPreferencesPlugin.register(with: registry.registrar(forPlugin: "SharedPreferencesPlugin")) }`
> 
> Runしたら、コード追加されたけど大丈夫そう？

こいつらpushしたらダメなやつ？
あと、 @ryu-k67 と同じ出力が出る

2023-12-04 07:06 UTC, sekibuuun reviewed
pubspec.lock  fading_edge_scrollview: dependency: transitive description: name: fading_edge_scrollview sha256: c25c2231652ce774cc31824d0112f11f653881f43d7f5302c05af11942052031 url: "https://pub.dev" source: hosted version: "3.0.0"

GeneratedPluginRegistrant.swift `// // Generated file. Do not edit. //

import FlutterMacOS import Foundation

import cloud_firestore import firebase_auth import firebase_core import firebase_storage import shared_preferences_foundation

func RegisterGeneratedPlugins(registry: FlutterPluginRegistry) { FLTFirebaseFirestorePlugin.register(with: registry.registrar(forPlugin: "FLTFirebaseFirestorePlugin")) FLTFirebaseAuthPlugin.register(with: registry.registrar(forPlugin: "FLTFirebaseAuthPlugin")) FLTFirebaseCorePlugin.register(with: registry.registrar(forPlugin: "FLTFirebaseCorePlugin")) FLTFirebaseStoragePlugin.register(with: registry.registrar(forPlugin: "FLTFirebaseStoragePlugin")) SharedPreferencesPlugin.register(with: registry.registrar(forPlugin: "SharedPreferencesPlugin")) }`

こいつらpushしたらダメなやつ？
あと、 @ryu-k67  と同じ出力が出る

2023-12-04 21:17 UTC, ryu-k67 commented
実行時エラーなし
見た目確認
フッター選択機能確認

2023-12-04 21:18 UTC, merged